name: Publish Docker

on:
  create:
    tag:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: soehms/khoca
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_API_TOKEN }}
        tag_names: true
