name: PyPI Deployer
on:
  push:
    tags:
      - "*" # Push events of new tags
  workflow_dispatch:
    # Allow to run manually

jobs:
  Linux-build:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USER }}
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: build and upload manylinux wheels
        uses: Niraj-Kamdar/manylinux-wheel-builder@master
